server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

spring:
  application:
    name: task-service
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url:
    username:
    password: ${db-password}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      simple:
        client:
          instances:
            identity-service[0]:
              uri: http://localhost:9000

custom:
  group:
    page_size: 20