server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api
  port: 8090
spring:
  application:
    name: task-service
  datasource:
    url:
    username:
    password:
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml
    enabled: true
    default-schema: public

  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host:
      port:
  main:
    banner-mode: off

app:
  default:
    page_size: 20
  group:
    page_size: 20
  task:
    page-size: 20